code-build.js, index.js
=> fix: add log entries before and after CodeBuild activity to differentiate GitHub log activity from CodeBuild log activity

README.md, action.yml, code-build.js, local.js, test/code-build-test.js
fixes: #17
rename input from env-passthrough to env-vars-for-codebuild
=> feat: rename input from env-passthrough to env-vars-for-codebuild

README.md, package.json
Bump version to 1.0.0 and add readme note about secrets access.
I also re-ran `npm run package`, but it looks like the version bump didn't change anything for that.
=> chore: Bump version to 1.0.0 and add readme note about secrets access

code-build.js
CloudWatchLog adds a line ending to each line.
`console.log` also adds a line ending.
I only need one.
I trimEnd and then `console.log` to ensure that the line ending is OS specific.
=> fix: CloudWatchLog line endings

local.js
The local script hard coded the remote name of `fork`.
Also, is should support `https` urls.
=> fix: update local script remote support

code-build.js, test/code-build-test.js
*Issue #, if available:* https://github.com/aws-actions/aws-codebuild-run-build/issues/28
- Increased the sleep timeout value from 5 seconds to 30 seconds to avoid API throttling when checking the status of the CodeBuild job.  In the issue, 60 seconds was thrown out as a value but I don't think it needs to be as long as that.  30 seconds should strike a good balance between not making too many API requests vs. not delaying the build too long.
=> Issue #28: Increase sleep timeout to prevent api rate limiting

code-build.js
UserAgent was incorrect: `aws-codbuild-run-project => aws-codebuild-run-build`
=> fix: useragent typo

package.json
*Description of changes:* Rebuild JS packages and bump version.
=> chore: rebuild and update to Version 1.0.2

code-build.js, local.js, test/code-build-test.js
The linting rules were not run on a specific change.
This formats things to clean up the codebase
This should simplify #40 by moving all the lint changes here.
=> fix: Run `npm format`

README.md
*Description of changes:* Change the version in the README example to v1 (instead of v1.0.0).
My coworkers and I were constantly getting the message "Waiting for DOWNLOAD_SOURCE" when creating pull requests, which then led to the error "Build status: FAILED".
We have been struggling with this problem for quite some time, and I recently realized that we were using an old version of this package because the example uses version 1.0.0, even though the most recent version is 1.0.3.
Most people who use this package will probably just copy the example, which means that they will be using an old version (v1.0.0) instead of the most recent version (v1.0.3 currently).
=> Change version to v1 instead of v1.0.0

README.md
Avoid having to update the example with every new version.
=> docs: use v1 tracking tag in README examples

.github/workflows/ci-unit-tests.yaml, action.yml, package-lock.json, package.json
Hi I'm recreating the PR from [here](https://github.com/aws-actions/aws-codebuild-run-build/pull/111) to get rid of the deprecations that are currently shown in GitHub Actions. This should be released until the 31 of May, otherwise every workflow using this action will stop working. See [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) for the announcement of GitHub.
https://github.com/aws-actions/aws-codebuild-run-build/issues/109
- Updates package.json dep @actions/core to version ^1.10.0
- Updates action.yml to node16
- Use newest versions of actions themselves
=> Update to node16 and bump actions core

README.md, action.yml, code-build.js, local.js, package-lock.json, test/code-build-test.js
_Issue #, if available:_ #76
_Description of changes:_
* Add configurable update interval and back-off time. Slight refactoring was required in order to transfer the values from the GitHub inputs to where they are used. SDK-specific configuration parameters and general action configuration values (currently just the update rate configuration) are treated slightly differently and are passed as separate objects to the building and waiting functions.
* Add new test for handling the update rate configuration
* Update existing tests where needed
* Add new inputs to action metadata file
* Update README.md
Default values are kept the same (30s interval, 15s back-off), so there should be no breakage when updating.
By submitting this pull request, I confirm that my contribution is made under the …
=> feat: Add configurable update rate

.github/workflows/package.yaml
*Issue #, if available:* https://github.com/aws-actions/aws-codebuild-run-build/pull/119
*Description of changes:* automatically update dist/index.js following the [amazon-ecr-login](https://github.com/aws-actions/amazon-ecr-login/blob/main/.github/workflows/package.yml) approach.
- [n] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.
=> Add packaging workflow, so that dist folder doesn't get out of date

README.md
none
before: `evn-passthrough`
after: `env-passthrough`
=> doc: fixed typo

code-build.js, test/code-build-test.js
*Issue #, if available:* seeing this error on the latest release https://github.com/taoyong-ty/aws-codebuild-run-build/actions/runs/4137008240/jobs/7151629480
This is because `disableSourceOverride` should not have been passed as an input to CodeBuild as input.
*Description of changes:* 
=> Fix an issue in inputs2Parameters(): `Error: Unexpected key 'disableSourceOverride' found in params`

README.md, action.yml, code-build.js, test/code-build-test.js
- Update the hide-cloudwatch-logs feature
- add some tests
=> Allow users to supress CloudWatch Logs

README.md
*Issue #, if available:* 
N/A
Last night at the time of writing, I noticed that the codebuild api allows users to pass in an inline definition of a buildspec file for buildspec-override.  In a project, I tried that out with this action and it worked. Figured it would be worth documenting for others to use if their use case calls for it.
=> Updating README with an example of doing an inline definition for buildspec-override.

README.md, action.yml, code-build.js, local.js, test/code-build-test.js
#140
Adds param for image-pull-credentials-type-override
=> Fixes #140

README.md, action.yml, code-build.js
*Issue #, if available:* 
#132
Add optional `source-version-override` to allow running CodeBuild from different `sourceVersion` than `aws-codebuild-run-build` action.
=> feat: Add sourceVersion override

README.md
Update documentation to reflect changes from https://github.com/aws-actions/aws-codebuild-run-build/pull/24
=> Use correct option name for env-vars-for-codebuild

code-build.js, package-lock.json, package.json, test/code-build-test.js
*Description of changes:* [Migrating your code to SDK for JavaScript V3](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html)
=> AWS SDK for JavaScript version 3 (v3) Upgrade

action.yml, code-build.js, test/code-build-test.js
https://github.com/aws-actions/aws-codebuild-run-build/issues/114
add non required `artifacts-type-override` to specify codebuild use a different or no artifaction location than it might be in a code pipeline run
=> allow artifacts type to be overridden

.github/workflows/publish.yaml
Getting the following warnings when using this action: `Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: aws-actions/aws-codebuild-run-build@v1.`
* Use NodeJS 20.x when building a package
* Use latest `actions/checkout` and `actions/setup-node`
=> Use Node20 for building

README.md
https://github.com/aws-actions/aws-codebuild-run-build/issues/114
READMe update for the 'artifacts-type-override' input. Support is already available in the code
=> README update for 'artifacts-type-override' input

README.md
*Description of changes:* CodeBuild recently launched another integration option for Github Action, so introducing this feature as a related feature in README 
=> Add an introduction of the new self-hosted-runner option to README

package-lock.json
Updated braces dependency to 3.0.3, as the previous version had known issues
- [n] Were any files moved? Moving files changes their URL, which breaks all hyperlinks to the files.
=> Update braces dependency to 3.0.3

package-lock.json
Ran np
```
fast-xml-parser  <4.4.1
Severity: high
fast-xml-parser vulnerable to ReDOS at currency parsing - https://github.com/advisories/GHSA-mpg4-rc92-vx8v
fix available via `npm audit fix`
node_modules/fast-xml-parser
@aws-sdk/client-sts  <=3.186.3 || 3.188.0 - 3.525.0
Depends on vulnerable versions of fast-xml-parser
node_modules/@aws-sdk/client-sts
@aws-sdk/client-cloudwatch-logs  3.12.0 - 3.525.0
Depends on vulnerable versions of @aws-sdk/client-sts
node_modules/@aws-sdk/client-cloudwatch-logs
@aws-sdk/client-codebuild  3.12.0 - 3.525.0
Depends on vulnerable versions of @aws-sdk/client-sts
node_modules/@aws-sdk/client-codebuild
4 high severity vulnerabilities
To address all issues, run:
npm audit fix
```
Ran npm audit fix:
```
npm WARN deprecated uuid@3.4.0: Please upgrade  to …
```
=> Updating dependencies to fix fast-xml-parser vulnerability CVE-2024-41818

README.md
*Issue #, if available:* https://github.com/aws-actions/aws-codebuild-run-build/issues/170
*Description of changes:* Updated README.md file to document workaround for npm 404 error during local testing. 
=> document workaround for npm 404 error on local
